import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { getAuthSession } from "@/utils/auth";

const poppins = Poppins({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Airbnb",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getAuthSession();
  console.log(session, "session");
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <div className="flex flex-col gap-2">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
